from django.contrib import admin
from django.urls import path
from home import views
from . import views

urlpatterns = [
   #path('', views.index, name='home'),
  # path("about", views.about, name='about'),
   #path("index", views.index, name='index'),
   path("yoga", views.yoga, name='yoga'),
   path('', views.Home, name='Home'),
   path('About', views.About, name='About'),
   path('herb', views.herb, name='herb'),
   path('medherb', views.medherb, name='medherb'),
   path('childyoga', views.childyoga, name='childyoga'),
   path('ai', views.ai, name='ai'),
   # path('get_ai_remedy', views.get_ai_remedy, name='get_ai_remedy'),
   path('healthform', views.healthform, name='healthform'),
   path('tulsi', views.tulsi, name='tulsi'),
   path('kapalbhati', views.kapalbhati, name='kapalbhati'),
   path('Treatment', views.Treatment, name='Treatment'),
   path('Fever', views.Fever, name='Fever'),
   path('Cold', views.Cold, name='Cold'),
   path('bodypain', views.bodypain, name='bodypain'),
   path('Headache', views.Headache, name='Headache'),
   path('Fatigue', views.Fatigue, name='Fatigue'),
   path('basic', views.basic, name='basic'),
   path('tadasana', views.tadasana, name='tadasana'),
   path('setubandhasana', views.setubandhasana, name='setubandhasana'),
   path('teenager', views.teenager, name='teenager'),
   path('kapalbhatiadult', views.kapalbhatiadult, name='kapalbhatiadult'),
   path('padmasana', views.padmasana, name='padmasana'),
   path('viparitakarani', views.viparitakarani, name='viparitakarani'),
   path('adhomukhasvanasana', views.adhomukhasvanasana, name='adhomukhasvanasana'),
   path('sukhasana', views.sukhasana, name='sukhasana'),
   path('suryana', views.suryana, name='suryana'),
   path('adult', views.adult, name='adult'),
   path('pranayama', views.pranayama, name='pranayama'),
   path('bhujangasana', views.bhujangasana, name='bhujangasana'),
   path('dhanurasana', views.dhanurasana, name='dhanurasana'),
   path('vrikshasana', views.vrikshasana, name='vrikshasana'),
   path('anulomvilom', views.anulomvilom, name='anulomvilom'),
   path('middleage', views.middleage, name='middleage'),
   path('shavasana', views.shavasana, name='shavasana'),
   path('shashankasana', views.shashankasana, name='shashankasana'),
   path('ardhamatsyendrasana', views.ardhamatsyendrasana, name='ardhamatsyendrasana'),
   path('ustrasana', views.ustrasana, name='ustrasana'),
   path('trikonasana', views.trikonasana, name='trikonasana'),
   path('apanasana', views.apanasana, name='apanasana'),
   path('seniors', views.seniors, name='seniors'),
   path('pavanamuktasana', views.pavanamuktasana, name='pavanamuktasana'),
   path('suptabaddhakonasana', views.suptabaddhakonasana, name='suptabaddhakonasana'),
   path('mentalhealth', views.mentalhealth, name='mentalhealth'),
   path('aromaherb', views.aromaherb, name="aromaherb"),
   path('culinherb', views.culinherb, name='culinherb'),
<<<<<<< HEAD
   path('baddhakonasana', views.baddhakonasana, name='baddhakonasana'),
   path('animalandfun', views.animalandfun, name='animalandfun'),
   path('marjariasana', views.marjariasana, name='marjariasana'),
   path('simhasana', views.simhasana, name='simhasana'),
   path('mandukasana', views.mandukasana, name='mandukasana'),
   path('matsyasana', views.matsyasana, name='matsyasana'),
   path('weakness', views.weakness, name='weakness'),
=======
   path('Termeric', views.Termeric, name='Termeric'),
>>>>>>> 01316d9bae573aac709d42308cb6390379420351
]